### ISSUE TITLE
The mapping is a big issue in the model prediction

### ISSUE THREAD

**Issue by chenscottus** [fan23j/yolov7-pose-whole-body#4]
Hi Jack,

     We have the similliar results like your examples: 
        https://github.com/fan23j/yolov7-pose-whole-body/tree/main/onnx_inference/

    The mapping is a big issue in the model prediction.

     Here are more examples from our training ( Left side is ground true, right side is prediction):
             

         ![pose_wb_comparison](https://user-images.githubusercontent.com/5216043/234075684-7b2fbd9b-422a-4d4f-afad-56ac8ac4e5a2.jpg)

**Comment by chenscottus** [comment]
https://user-images.githubusercontent.com/5216043/234075684-7b2fbd9b-422a-4d4f-afad-56ac8ac4e5a2.jpg

**Comment by fan23j** [comment]
Am training another model to see if I can debug the issue

**Comment by chenscottus** [comment]
Here is the result after we re-training the model:
![test2](https://user-images.githubusercontent.com/5216043/235494413-1604f485-7663-4a78-8f42-1cb288bb2bda.jpg)

There is Only a little improvement in performance but the results are very poor.

Thanks,

-Scott

**Comment by fan23j** [comment]
What is the mAP after training? Do the images drawn in mosaic through `test.py` also present this mapping issue? I presume it's not a performance issue but rather a mapping one.

**Comment by chenscottus** [comment]
it was somewhere around 0.78 after training. The images drawn in mosaic
through test.py also present this mapping issue.

**Comment by fan23j** [comment]
#5
